// Mapa de todas as categorias do projeto.
// "ready: true" = já tem receitas completas em data/<id>.js
// "ready: false" = ainda não foi escrita (aparece como "em breve" no menu)
window.CATEGORIES = [
  { group: "Fundamentos", id: "molhos", label: "Molhos Clássicos", desc: "A base de praticamente toda cozinha ocidental.", ready: true },
  { group: "Fundamentos", id: "sopas", label: "Sopas", ready: true },
  { group: "Fundamentos", id: "entradas-frias", label: "Entradas", ready: true },
  { group: "Fundamentos", id: "entradas-quentes", label: "Entradas", ready: true },
  { group: "Fundamentos", id: "massas", label: "Massas", ready: true },
  { group: "Fundamentos", id: "risotos", label: "Risotos/Arroz", ready: true },
  { group: "Fundamentos", id: "ovos-basicos", label: "Ovos", ready: true },
  { group: "Fundamentos", id: "ovos-classicos", label: "Ovos", ready: true },
  { group: "Fundamentos", id: "padaria", label: "Padaria", ready: true },
  { group: "Fundamentos", id: "sobremesas-classicas", label: "Sobremesas", ready: true },
  { group: "Fundamentos", id: "contemporaneos", label: "Técnicas", ready: true },
  { group: "Fundamentos", id: "tecnicas-contemporaneas-2", label: "Técnicas", ready: true },

  { group: "Proteínas", id: "aves", label: "Aves", ready: true },
  { group: "Proteínas", id: "carnes-bovinas", label: "Carnes Bovinas", ready: true },
  { group: "Proteínas", id: "cordeiro", label: "Cordeiro", ready: true },
  { group: "Proteínas", id: "suinos", label: "Suínos", ready: true },
  { group: "Proteínas", id: "peixes", label: "Peixes", ready: true },
  { group: "Proteínas", id: "frutos-do-mar", label: "Frutos do Mar", ready: true },
  { group: "Proteínas", id: "arrozes", label: "Risotos/Arroz", ready: true },

  { group: "Brasil", id: "brasileiros", label: "Brasileiros Obrigatórios", ready: true },
  { group: "Brasil", id: "brasil-regional", label: "Brasil por Região", ready: true },

  { group: "Países", id: "franca", label: window.COUNTRIES.franca.nome, ready: true },
  { group: "Países", id: "italia", label: window.COUNTRIES.italia.nome, ready: true },
  { group: "Países", id: "espanha", label: window.COUNTRIES.espanha.nome, ready: true },
  { group: "Países", id: "portugal", label: window.COUNTRIES.portugal.nome, ready: true },
  { group: "Países", id: "japao", label: window.COUNTRIES.japao.nome, ready: true },
  { group: "Países", id: "china", label: window.COUNTRIES.china.nome, ready: true },
  { group: "Países", id: "coreia", label: window.COUNTRIES.coreia.nome, ready: true },
  { group: "Países", id: "tailandia", label: window.COUNTRIES.tailandia.nome, ready: true },
  { group: "Países", id: "india", label: window.COUNTRIES.india.nome, ready: true },
  { group: "Países", id: "mexico", label: window.COUNTRIES.mexico.nome, ready: true },
  { group: "Países", id: "peru", label: window.COUNTRIES.peru.nome, ready: true },
  { group: "Países", id: "alemanha", label: window.COUNTRIES.alemanha.nome, ready: true },
  { group: "Países", id: "austria", label: window.COUNTRIES.austria.nome, ready: true },
  { group: "Países", id: "hungria", label: window.COUNTRIES.hungria.nome, ready: true },
  { group: "Países", id: "grecia", label: window.COUNTRIES.grecia.nome, ready: true },
  { group: "Países", id: "marrocos", label: window.COUNTRIES.marrocos.nome, ready: true },
  { group: "Países", id: "libano", label: window.COUNTRIES.libano.nome, ready: true },
  { group: "Países", id: "eua", label: window.COUNTRIES.eua.nome, ready: true },
  { group: "Países", id: "dinamarca", label: window.COUNTRIES.dinamarca.nome, ready: true },
];
