// Mapa de todas as categorias do projeto.
// "ready: true" = já tem receitas completas em data/<id>.js
// "ready: false" = ainda não foi escrita (aparece como "em breve" no menu)
window.CATEGORIES = [
  { group: "Fundamentos", id: "molhos", label: "Molhos Clássicos", icon: "🥣", desc: "A base de praticamente toda cozinha ocidental.", ready: true },
  { group: "Fundamentos", id: "sopas", label: "Sopas", icon: "🍲", ready: true },
  { group: "Fundamentos", id: "entradas-frias", label: "Entradas", icon: "🥗", ready: true },
  { group: "Fundamentos", id: "entradas-quentes", label: "Entradas", icon: "🥗", ready: true },
  { group: "Fundamentos", id: "massas", label: "Massas", icon: "🍝", ready: true },
  { group: "Fundamentos", id: "risotos", label: "Risotos/Arroz", icon: "🍚", ready: true },
  { group: "Fundamentos", id: "ovos-basicos", label: "Ovos", icon: "🥚", ready: true },
  { group: "Fundamentos", id: "ovos-classicos", label: "Ovos", icon: "🥚", ready: true },
  { group: "Fundamentos", id: "padaria", label: "Padaria", icon: "🍞", ready: true },
  { group: "Fundamentos", id: "sobremesas-classicas", label: "Sobremesas", icon: "🍰", ready: true },
  { group: "Fundamentos", id: "contemporaneos", label: "Técnicas", icon: "🧪", ready: true },
  { group: "Fundamentos", id: "tecnicas-contemporaneas-2", label: "Técnicas", icon: "🧪", ready: true },

  { group: "Proteínas", id: "aves", label: "Aves", icon: "🍗", ready: true },
  { group: "Proteínas", id: "carnes-bovinas", label: "Carnes Bovinas", icon: "🥩", ready: true },
  { group: "Proteínas", id: "cordeiro", label: "Cordeiro", icon: "🐑", ready: true },
  { group: "Proteínas", id: "suinos", label: "Suínos", icon: "🐖", ready: true },
  { group: "Proteínas", id: "peixes", label: "Peixes", icon: "🐟", ready: true },
  { group: "Proteínas", id: "frutos-do-mar", label: "Frutos do Mar", icon: "🦐", ready: true },
  { group: "Proteínas", id: "arrozes", label: "Risotos/Arroz", icon: "🍚", ready: true },

  { group: "Brasil", id: "brasileiros", label: "Brasileiros Obrigatórios", icon: "🇧🇷", ready: true },
  { group: "Brasil", id: "brasil-regional", label: "Brasil por Região", icon: "🗺️", ready: true },

  { group: "Países", id: "franca", label: "França", icon: "🇫🇷", ready: true },
  { group: "Países", id: "italia", label: "Itália", icon: "🇮🇹", ready: true },
  { group: "Países", id: "espanha", label: "Espanha", icon: "🇪🇸", ready: true },
  { group: "Países", id: "portugal", label: "Portugal", icon: "🇵🇹", ready: true },
  { group: "Países", id: "japao", label: "Japão", icon: "🇯🇵", ready: true },
  { group: "Países", id: "china", label: "China", icon: "🇨🇳", ready: true },
  { group: "Países", id: "coreia", label: "Coreia", icon: "🇰🇷", ready: true },
  { group: "Países", id: "tailandia", label: "Tailândia", icon: "🇹🇭", ready: true },
  { group: "Países", id: "india", label: "Índia", icon: "🇮🇳", ready: true },
  { group: "Países", id: "mexico", label: "México", icon: "🇲🇽", ready: true },
  { group: "Países", id: "peru", label: "Peru", icon: "🇵🇪", ready: true },
  { group: "Países", id: "alemanha", label: "Alemanha", icon: "🇩🇪", ready: true },
  { group: "Países", id: "austria", label: "Áustria", icon: "🇦🇹", ready: true },
  { group: "Países", id: "hungria", label: "Hungria", icon: "🇭🇺", ready: true },
  { group: "Países", id: "grecia", label: "Grécia", icon: "🇬🇷", ready: true },
  { group: "Países", id: "marrocos", label: "Marrocos", icon: "🇲🇦", ready: true },
  { group: "Países", id: "libano", label: "Líbano", icon: "🇱🇧", ready: true },
  { group: "Países", id: "eua", label: "EUA", icon: "🇺🇸", ready: true },
  { group: "Países", id: "dinamarca", label: "Dinamarca", icon: "🇩🇰", ready: true },
];
